### ISSUE TITLE
Failed to run flannel in AliCloud with vpc

### ISSUE THREAD

**Issue by echokk11** [flannel-io/flannel#1023]
Failed to run flannel in AliCloud with vpc

## Expected Behavior
worked

## Current Behavior
fatal error: unexpected signal during runtime execution

## Steps to Reproduce (for bugs)
1. I have export ACCESS_KEY_ID & ACCESS_KEY_SECRET
2. connect to ETCD with ca
3. set /coreos.com/network/config '{"Network":"10.200.0.0/16", "Backend": {"Type": "ali-vpc"}}'  successful
4. 
```
./flanneld --etcd-endpoints=https://172.16.1.38:2379,https://172.16.2.82:2379 \
--etcd-cafile=/var/lib/kubernetes/ca.pem \
--etcd-certfile=/var/lib/kubernetes/kubernetes.pem \
--etcd-keyfile=/var/lib/kubernetes/kubernetes-key.pem
```
5. it is not working
```
I0725 15:15:37.509202   28625 main.go:475] Determining IP address of default interface
I0725 15:15:37.509814   28625 main.go:488] Using interface with name eth0 and address 172.16.1.38
I0725 15:15:37.509845   28625 main.go:505] Defaulting external address to interface address (172.16.1.38)
2018-07-25 15:15:37.510831 I | warning: ignoring ServerName for user-provided CA for backwards compatibility is deprecated
I0725 15:15:37.510932   28625 main.go:235] Created subnet manager: Etcd Local Manager with Previous Subnet: None
I0725 15:15:37.510948   28625 main.go:238] Installing signal handlers
I0725 15:15:37.529672   28625 main.go:353] Found network config - Backend type: ali-vpc
I0725 15:15:37.529756   28625 alivpc.go:63] Unmarshal Configure : { }
I0725 15:15:37.537943   28625 local_manager.go:147] Found lease (10.200.93.0/24) for current IP (172.16.1.38), reusing
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x63 pc=0x7f85fd7c360d]

runtime stack:
runtime.throw(0x1a7f7cf, 0x2a)
	/usr/local/go/src/runtime/panic.go:605 +0x95
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:351 +0x2b8

goroutine 71 [syscall, locked to thread]:
runtime.cgocall(0x15273b0, 0xc42002dde8, 0x1a7d72e)
	/usr/local/go/src/runtime/cgocall.go:132 +0xe4 fp=0xc42002dda8 sp=0xc42002dd68 pc=0x402514
net._C2func_getaddrinfo(0x7f85ec0008c0, 0x0, 0xc420218420, 0xc420104240, 0x0, 0x0, 0x0)
	net/_obj/_cgo_gotypes.go:86 +0x5f fp=0xc42002dde8 sp=0xc42002dda8 pc=0x52081f
net.cgoLookupIPCNAME.func2(0x7f85ec0008c0, 0x0, 0xc420218420, 0xc420104240, 0xc4200ffd40, 0xc42047fc00, 0x1c)
	/usr/local/go/src/net/cgo_unix.go:151 +0x13f fp=0xc42002de40 sp=0xc42002dde8 pc=0x527dbf
net.cgoLookupIPCNAME(0xc42047fc00, 0x1c, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/cgo_unix.go:151 +0x175 fp=0xc42002df38 sp=0xc42002de40 pc=0x522075
net.cgoIPLookup(0xc4200ffe00, 0xc42047fc00, 0x1c)
	/usr/local/go/src/net/cgo_unix.go:203 +0x4d fp=0xc42002dfc8 sp=0xc42002df38 pc=0x5227bd
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc42002dfd0 sp=0xc42002dfc8 pc=0x4598f1
created by net.cgoLookupIP
	/usr/local/go/src/net/cgo_unix.go:213 +0xaf

goroutine 1 [select]:
net/http.(*Transport).getConn(0x282d8a0, 0xc4202c7e60, 0x0, 0xc420168160, 0x5, 0xc42047fc00, 0x20, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:948 +0x5bf
net/http.(*Transport).RoundTrip(0x282d8a0, 0xc42012b400, 0x282d8a0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:400 +0x6a6
net/http.send(0xc42012b400, 0x283d5a0, 0x282d8a0, 0x0, 0x0, 0x0, 0xc420104210, 0x7f85fc09d0b8, 0xc4205cb510, 0x1)
	/usr/local/go/src/net/http/client.go:249 +0x1a9
net/http.(*Client).send(0xc4202c7d10, 0xc42012b400, 0x0, 0x0, 0x0, 0xc420104210, 0x0, 0x1, 0x7f85fc08dda8)
	/usr/local/go/src/net/http/client.go:173 +0xfd
net/http.(*Client).Do(0xc4202c7d10, 0xc42012b400, 0x28a9140, 0x1a54d68, 0x1)
	/usr/local/go/src/net/http/client.go:602 +0x28d
github.com/coreos/flannel/vendor/github.com/denverdino/aliyungo/common.(*Client).Invoke(0xc4204d8510, 0x1a5dbc6, 0xc, 0x1811720, 0xc4202c7d40, 0x17b9cc0, 0xc4203b5340, 0x0, 0x0)
	/go/src/github.com/coreos/flannel/vendor/github.com/denverdino/aliyungo/common/client.go:143 +0x469
github.com/coreos/flannel/vendor/github.com/denverdino/aliyungo/ecs.(*Client).DescribeVpcs(0xc4204d8510, 0xc4202c7d40, 0xc420018012, 0x1e, 0xc4204d8510, 0x0, 0x0, 0x80)
	/go/src/github.com/coreos/flannel/vendor/github.com/denverdino/aliyungo/ecs/vpcs.go:101 +0x9b
github.com/coreos/flannel/backend/alivpc.(*AliVpcBackend).RegisterNetwork(0xc420286ec0, 0x7f85fd9e2288, 0xc4203b4e00, 0xc420156f50, 0xc420286ec0, 0x0, 0x0, 0xa00205cbd00)
	/go/src/github.com/coreos/flannel/backend/alivpc/alivpc.go:105 +0x6eb
main.main()
	/go/src/github.com/coreos/flannel/main.go:278 +0x7a0

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:131 +0xa6
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 6 [chan receive]:
github.com/coreos/flannel/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x28a94c0)
	/go/src/github.com/coreos/flannel/vendor/github.com/golang/glog/glog.go:879 +0x9f
created by github.com/coreos/flannel/vendor/github.com/golang/glog.init.0
	/go/src/github.com/coreos/flannel/vendor/github.com/golang/glog/glog.go:410 +0x203

goroutine 8 [select, locked to thread]:
runtime.gopark(0x1ad26a0, 0x0, 0x1a58035, 0x6, 0x18, 0x1)
	/usr/local/go/src/runtime/proc.go:287 +0x12c
runtime.selectgo(0xc420293f50, 0xc4202523c0)
	/usr/local/go/src/runtime/select.go:395 +0x1149
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal_unix.go:511 +0x220
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2337 +0x1

goroutine 9 [select]:
main.shutdownHandler(0x7f85fd9e2288, 0xc4203b4e00, 0xc4200feb40, 0xc42022d710)
	/go/src/github.com/coreos/flannel/main.go:331 +0xf2
main.main.func1(0x7f85fd9e2288, 0xc4203b4e00, 0xc4200feb40, 0xc42022d710, 0xc4201d2970)
	/go/src/github.com/coreos/flannel/main.go:252 +0x49
created by main.main
	/go/src/github.com/coreos/flannel/main.go:251 +0x553

goroutine 15 [chan receive]:
github.com/coreos/flannel/backend.(*manager).GetBackend.func1(0xc420156fa0, 0xc4201d2b68, 0x7)
	/go/src/github.com/coreos/flannel/backend/manager.go:75 +0x4e
created by github.com/coreos/flannel/backend.(*manager).GetBackend
	/go/src/github.com/coreos/flannel/backend/manager.go:74 +0x258

goroutine 34 [IO wait]:
internal/poll.runtime_pollWait(0x7f85fd9e0eb0, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc4202be818, 0x72, 0xffffffffffffff00, 0x2840460, 0x2835f60)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc4202be818, 0xc4204ae000, 0x800, 0x800)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc4202be800, 0xc4204ae000, 0x800, 0x800, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:126 +0x18a
net.(*netFD).Read(0xc4202be800, 0xc4204ae000, 0x800, 0x800, 0x3, 0xc42003d780, 0x556078)
	/usr/local/go/src/net/fd_unix.go:202 +0x52
net.(*conn).Read(0xc420104180, 0xc4204ae000, 0x800, 0x800, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:176 +0x6d
crypto/tls.(*block).readFromUntil(0xc420294030, 0x7f85fd9e22c8, 0xc420104180, 0x5, 0xc420104180, 0xc4202c7710)
	/usr/local/go/src/crypto/tls/conn.go:488 +0x95
crypto/tls.(*Conn).readRecord(0xc4204dc000, 0x1ad2717, 0xc4204dc120, 0x42cd9b)
	/usr/local/go/src/crypto/tls/conn.go:590 +0xe0
crypto/tls.(*Conn).Read(0xc4204dc000, 0xc420493000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1134 +0x110
net/http.(*persistConn).Read(0xc42049e120, 0xc420493000, 0x1000, 0x1000, 0xc4201d2980, 0xc420076238, 0x453b70)
	/usr/local/go/src/net/http/transport.go:1391 +0x140
bufio.(*Reader).fill(0xc4202102a0)
	/usr/local/go/src/bufio/bufio.go:97 +0x11a
bufio.(*Reader).Peek(0xc4202102a0, 0x1, 0x0, 0x0, 0x0, 0xc4205f2300, 0x0)
	/usr/local/go/src/bufio/bufio.go:129 +0x3a
net/http.(*persistConn).readLoop(0xc42049e120)
	/usr/local/go/src/net/http/transport.go:1539 +0x185
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1186 +0xa2e

goroutine 35 [select]:
net/http.(*persistConn).writeLoop(0xc42049e120)
	/usr/local/go/src/net/http/transport.go:1759 +0x165
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1187 +0xa53

goroutine 54 [IO wait]:
internal/poll.runtime_pollWait(0x7f85fd9e0df0, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc4202beb18, 0x72, 0xffffffffffffff00, 0x2840460, 0x2835f60)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc4202beb18, 0xc420560000, 0x1000, 0x1000)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc4202beb00, 0xc420560000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:126 +0x18a
net.(*netFD).Read(0xc4202beb00, 0xc420560000, 0x1000, 0x1000, 0x42cd9b, 0xc42003ba40, 0x455980)
	/usr/local/go/src/net/fd_unix.go:202 +0x52
net.(*conn).Read(0xc42000e4d0, 0xc420560000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:176 +0x6d
net/http.(*persistConn).Read(0xc42049e7e0, 0xc420560000, 0x1000, 0x1000, 0xc42047eb80, 0xc420252dd8, 0x453b70)
	/usr/local/go/src/net/http/transport.go:1391 +0x140
bufio.(*Reader).fill(0xc4200506c0)
	/usr/local/go/src/bufio/bufio.go:97 +0x11a
bufio.(*Reader).Peek(0xc4200506c0, 0x1, 0x0, 0x0, 0x0, 0xc4205f2480, 0x0)
	/usr/local/go/src/bufio/bufio.go:129 +0x3a
net/http.(*persistConn).readLoop(0xc42049e7e0)
	/usr/local/go/src/net/http/transport.go:1539 +0x185
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1186 +0xa2e

goroutine 55 [select]:
net/http.(*persistConn).writeLoop(0xc42049e7e0)
	/usr/local/go/src/net/http/transport.go:1759 +0x165
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1187 +0xa53

goroutine 69 [select]:
net.(*Resolver).LookupIPAddr(0x28a7580, 0x284d920, 0xc4200ffd40, 0xc42047fc00, 0x1c, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/lookup.go:196 +0x52b
net.(*Resolver).internetAddrList(0x28a7580, 0x284d920, 0xc4200ffd40, 0x1a55550, 0x3, 0xc42047fc00, 0x20, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/ipsock.go:293 +0x644
net.(*Resolver).resolveAddrList(0x28a7580, 0x284d920, 0xc4200ffd40, 0x1a55bae, 0x4, 0x1a55550, 0x3, 0xc42047fc00, 0x20, 0x0, ...)
	/usr/local/go/src/net/dial.go:193 +0x594
net.(*Dialer).DialContext(0xc42005e120, 0x284d8e0, 0xc420016078, 0x1a55550, 0x3, 0xc42047fc00, 0x20, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/dial.go:375 +0x248
net.(*Dialer).DialContext-fm(0x284d8e0, 0xc420016078, 0x1a55550, 0x3, 0xc42047fc00, 0x20, 0x404409, 0x60, 0x61abc9, 0xc420016078)
	/usr/local/go/src/net/http/transport.go:46 +0x73
net/http.(*Transport).dial(0x282d8a0, 0x284d8e0, 0xc420016078, 0x1a55550, 0x3, 0xc42047fc00, 0x20, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/http/transport.go:884 +0x223
net/http.(*Transport).dialConn(0x282d8a0, 0x284d8e0, 0xc420016078, 0x0, 0xc420168160, 0x5, 0xc42047fc00, 0x20, 0xc420252cc0, 0x5262e4, ...)
	/usr/local/go/src/net/http/transport.go:1060 +0x1d62
net/http.(*Transport).getConn.func4(0x282d8a0, 0x284d8e0, 0xc420016078, 0xc4202c7e90, 0xc420252ea0)
	/usr/local/go/src/net/http/transport.go:943 +0x78
created by net/http.(*Transport).getConn
	/usr/local/go/src/net/http/transport.go:942 +0x393

goroutine 70 [select]:
net.cgoLookupIP(0x284d920, 0xc4200ffd40, 0xc42047fc00, 0x1c, 0xc42002dda8, 0x455980, 0xc42006b200, 0x4, 0xc42002ddf8, 0x404e7c)
	/usr/local/go/src/net/cgo_unix.go:214 +0x1b0
net.(*Resolver).lookupIP(0x28a7580, 0x284d920, 0xc4200ffd40, 0xc42047fc00, 0x1c, 0xc42002de88, 0x3, 0xc42002df40, 0x0, 0x2)
	/usr/local/go/src/net/lookup_unix.go:95 +0x12d
net.(*Resolver).(net.lookupIP)-fm(0x284d920, 0xc4200ffd40, 0xc42047fc00, 0x1c, 0x283d620, 0xc420252d78, 0x453b70, 0xc420252d20, 0xc42002ded0)
	/usr/local/go/src/net/lookup.go:187 +0x56
net.glob..func10(0x284d920, 0xc4200ffd40, 0xc42022dd20, 0xc42047fc00, 0x1c, 0x526323, 0xc420252d20, 0x1bb38e0, 0x0, 0x0)
	/usr/local/go/src/net/hook.go:19 +0x52
net.(*Resolver).LookupIPAddr.func1(0x282d8a0, 0x284d8e0, 0xc420016078, 0x0)
	/usr/local/go/src/net/lookup.go:193 +0x5c
internal/singleflight.(*Group).doCall(0x28a7570, 0xc420157040, 0xc42047fc00, 0x1c, 0xc4202c7f20)
	/usr/local/go/src/internal/singleflight/singleflight.go:93 +0x2e
created by internal/singleflight.(*Group).DoChan
	/usr/local/go/src/internal/singleflight/singleflight.go:86 +0x31f
```

## Your Environment

* Flannel version: v0.10.0
* Backend used (e.g. vxlan or udp): ali-vpc
* Etcd version: 3.3.8
* Kubernetes version (if used):
* Operating System and version: Linux k8s-node1 3.10.0-862.6.3.el7.x86_64 #1 SMP Tue Jun 26 16:32:21 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.5.1804 (Core)
Release:	7.5.1804
Codename:	Core
```
* Link to your project (optional):

**Comment by echokk11** [comment]
but it works in another node.
```
/home/ngariHZ/flanneld --etcd-endpoints=https://172.16.1.38:2379,https://172.16.2.82:2379 \
> --etcd-cafile=/var/lib/kubernetes/ca.pem \
> --etcd-certfile=/var/lib/kubernetes/kubernetes.pem \
> --etcd-keyfile=/var/lib/kubernetes/kubernetes-key.pem
I0726 11:00:40.366100   10791 main.go:475] Determining IP address of default interface
I0726 11:00:40.366407   10791 main.go:488] Using interface with name eth0 and address 172.16.2.82
I0726 11:00:40.366423   10791 main.go:505] Defaulting external address to interface address (172.16.2.82)
2018-07-26 11:00:40.367120 I | warning: ignoring ServerName for user-provided CA for backwards compatibility is deprecated
I0726 11:00:40.367175   10791 main.go:235] Created subnet manager: Etcd Local Manager with Previous Subnet: 10.200.30.0/24
I0726 11:00:40.367182   10791 main.go:238] Installing signal handlers
I0726 11:00:40.391856   10791 main.go:353] Found network config - Backend type: ali-vpc
I0726 11:00:40.391918   10791 alivpc.go:63] Unmarshal Configure : { }
I0726 11:00:40.405122   10791 local_manager.go:147] Found lease (10.200.30.0/24) for current IP (172.16.2.82), reusing
I0726 11:00:41.018413   10791 alivpc.go:164] Keep target entry: rtableid=vtb-23przw1rz, CIDR=10.200.30.0/24, NextHop=i-bp1ggd58nxvl4mqlqisl
I0726 11:00:41.018440   10791 alivpc.go:187] Keep route entry: rtableid=vtb-23przw1rz, CIDR=192.168.0.0/16, NextHop=i-bp1aslokq5ljn2cpyzv8
I0726 11:00:41.018449   10791 alivpc.go:187] Keep route entry: rtableid=vtb-23przw1rz, CIDR=172.26.0.0/24, NextHop=VCON-0lb1ut1q3
I0726 11:00:41.018475   10791 alivpc.go:187] Keep route entry: rtableid=vtb-23przw1rz, CIDR=10.128.0.0/9, NextHop=VCON-0lb1ut1q3
I0726 11:00:41.018484   10791 alivpc.go:187] Keep route entry: rtableid=vtb-23przw1rz, CIDR=10.0.0.0/9, NextHop=VCON-0lb1ut1q3
I0726 11:00:41.018492   10791 alivpc.go:187] Keep route entry: rtableid=vtb-23przw1rz, CIDR=172.16.1.0/24, NextHop=
I0726 11:00:41.018499   10791 alivpc.go:187] Keep route entry: rtableid=vtb-23przw1rz, CIDR=172.16.2.0/24, NextHop=
I0726 11:00:41.018507   10791 alivpc.go:187] Keep route entry: rtableid=vtb-23przw1rz, CIDR=100.64.0.0/10, NextHop=
I0726 11:00:41.200829   10791 main.go:300] Wrote subnet file to /run/flannel/subnet.env
I0726 11:00:41.200856   10791 main.go:304] Running backend.
I0726 11:00:41.207778   10791 main.go:396] Waiting for 22h59m59.199404331s to renew lease
```

the 2 alicloud is the same.

**Comment by tuxknight** [comment]
It will work in version 0.8.
