### ISSUE TITLE
fatal error: unexpected signal during runtime execution [signal SIGSEGV: segmentation violation code=0x1 addr=0xe5 pc=0x7f67d0cca0f1]

### ISSUE THREAD

**Issue by szbjb** [flannel-io/flannel#1418]
```
CentOS Stream release 8
4.18.0-277.el8.x86_64
flannel-v0.13

```

`[root@stream8-30 Software_package]# /usr/local/bin/flanneld --ip-masq   --etcd-endpoints=http://192.168.3.30:2379 -etcd-cafile=/etc/etcd/ssl/ca.pem -etcd-certfile=/etc/etcd/ssl/server.pem -etcd-keyfile=/etc/etcd/ssl/server-key.pem
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xe5 pc=0x7f67d0cca0f1]

runtime stack:
runtime.throw(0x20c058e, 0x2a)
	/usr/local/go/src/runtime/panic.go:1116 +0x72
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:726 +0x4ac

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x1a4d360, 0xc000068bd0, 0xc000130020)
	/usr/local/go/src/runtime/cgocall.go:133 +0x5b fp=0xc000068ba0 sp=0xc000068b68 pc=0x40571b
os/user._Cfunc_mygetpwuid_r(0x0, 0xc000114db0, 0x45fe0b0, 0x400, 0xc000130020, 0x7f6700000000)
	_cgo_gotypes.go:175 +0x4d fp=0xc000068bd0 sp=0xc000068ba0 pc=0x7a456d
os/user.lookupUnixUid.func1.1(0x0, 0xc000114db0, 0xc000112c50, 0xc000130020, 0xc000068c70)
	/usr/local/go/src/os/user/cgo_lookup_unix.go:103 +0xd0 fp=0xc000068c20 sp=0xc000068bd0 pc=0x7a5ad0
os/user.lookupUnixUid.func1(0x1e049a0)
	/usr/local/go/src/os/user/cgo_lookup_unix.go:103 +0x45 fp=0xc000068c58 sp=0xc000068c20 pc=0x7a5b45
os/user.retryWithBuffer(0xc000112c50, 0xc000068d30, 0x0, 0x0)
	/usr/local/go/src/os/user/cgo_lookup_unix.go:247 +0x3e fp=0xc000068cb0 sp=0xc000068c58 pc=0x7a509e
os/user.lookupUnixUid(0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/os/user/cgo_lookup_unix.go:96 +0x132 fp=0xc000068d78 sp=0xc000068cb0 pc=0x7a49b2
os/user.current(0x0, 0x0, 0x0)
	/usr/local/go/src/os/user/cgo_lookup_unix.go:49 +0x49 fp=0xc000068db8 sp=0xc000068d78 pc=0x7a4849
os/user.Current.func1()
	/usr/local/go/src/os/user/lookup.go:15 +0x25 fp=0xc000068de0 sp=0xc000068db8 pc=0x7a5985
sync.(*Once).doSlow(0x2f9ed80, 0x214c128)
	/usr/local/go/src/sync/once.go:66 +0xec fp=0xc000068e30 sp=0xc000068de0 pc=0x4863cc
sync.(*Once).Do(...)
	/usr/local/go/src/sync/once.go:57
os/user.Current(0xc00012c2d0, 0xa, 0x20874b5)
	/usr/local/go/src/os/user/lookup.go:15 +0x105 fp=0xc000068e60 sp=0xc000068e30 pc=0x7a4265
k8s.io/klog.init.1()
	/go/src/github.com/coreos/flannel/vendor/k8s.io/klog/klog_file.go:58 +0x45 fp=0xc000068ec8 sp=0xc000068e60 pc=0x7aa585
runtime.doInit(0x2f40280)
	/usr/local/go/src/runtime/proc.go:5646 +0x8a fp=0xc000068ef8 sp=0xc000068ec8 pc=0x44760a
runtime.doInit(0x2f3a760)
	/usr/local/go/src/runtime/proc.go:5641 +0x57 fp=0xc000068f28 sp=0xc000068ef8 pc=0x4475d7
runtime.doInit(0x2f36f40)
	/usr/local/go/src/runtime/proc.go:5641 +0x57 fp=0xc000068f58 sp=0xc000068f28 pc=0x4475d7
runtime.doInit(0x2f44220)
	/usr/local/go/src/runtime/proc.go:5641 +0x57 fp=0xc000068f88 sp=0xc000068f58 pc=0x4475d7
runtime.main()
	/usr/local/go/src/runtime/proc.go:191 +0x1c5 fp=0xc000068fe0 sp=0xc000068f88 pc=0x43a405
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc000068fe8 sp=0xc000068fe0 pc=0x46d481

goroutine 19 [chan receive]:
k8s.io/klog.(*loggingT).flushDaemon(0x2f9fbe0)
	/go/src/github.com/coreos/flannel/vendor/k8s.io/klog/klog.go:1010 +0x8b
created by k8s.io/klog.init.0
	/go/src/github.com/coreos/flannel/vendor/k8s.io/klog/klog.go:411 +0xd8
`

**Comment by zhangguanzhang** [comment]
你是不是开了安全软件啥的

**Comment by szbjb** [comment]
> 你是不是开了安全软件啥的
没有啊 . 再怎么开安全软件 不应该 执行这个命令都报错啊 
flanneld  -version

**Comment by szbjb** [comment]
> 你是不是开了安全软件啥的

centos7.x正常

**Comment by zhangguanzhang** [comment]
你下的是rc的版本吗，是release的话换12的试试

**Comment by szbjb** [comment]
> 你下的是rc的版本吗，是release的话换12的试试

rc  或者12都试过
`
[root@stream8-40 ~]# md5sum  flanneld
ecd7b08f48c38e95305fab35f5b9f2e8  flanneld
[root@stream8-40 ~]# md5sum flannel-v0.13.1-rc2-linux-amd64.tar.gz
17381a0ef1344862a51471e75b3b810d  flannel-v0.13.1-rc2-linux-amd64.tar.gz
[root@stream8-40 ~]# ./flanneld  -version
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xe5 pc=0x7f59341600f1]

runtime stack:
runtime.throw(0x20c058e, 0x2a)
	/usr/local/go/src/runtime/panic.go:1116 +0x72
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:726 +0x4ac

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x1a4d360, 0xc00006bbd0, 0xc000010030)
	/usr/local/go/src/runtime/cgocall.go:133 +0x5b fp=0xc00006bba0 sp=0xc00006bb68 pc=0x40571b
os/user._Cfunc_mygetpwuid_r(0x0, 0xc000098db0, 0x323c0b0, 0x400, 0xc000010030, 0x7f5900000000)
	_cgo_gotypes.go:175 +0x4d fp=0xc00006bbd0 sp=0xc00006bba0 pc=0x7a456d
os/user.lookupUnixUid.func1.1(0x0, 0xc000098db0, 0xc000048c70, 0xc000010030, 0xc00006bc70)
	/usr/local/go/src/os/user/cgo_lookup_unix.go:103 +0xd0 fp=0xc00006bc20 sp=0xc00006bbd0 pc=0x7a5ad0
os/user.lookupUnixUid.func1(0x1e049a0)
	/usr/local/go/src/os/user/cgo_lookup_unix.go:103 +0x45 fp=0xc00006bc58 sp=0xc00006bc20 pc=0x7a5b45
os/user.retryWithBuffer(0xc000048c70, 0xc00006bd30, 0x0, 0x0)
	/usr/local/go/src/os/user/cgo_lookup_unix.go:247 +0x3e fp=0xc00006bcb0 sp=0xc00006bc58 pc=0x7a509e
os/user.lookupUnixUid(0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/os/user/cgo_lookup_unix.go:96 +0x132 fp=0xc00006bd78 sp=0xc00006bcb0 pc=0x7a49b2
os/user.current(0x0, 0x0, 0x0)
	/usr/local/go/src/os/user/cgo_lookup_unix.go:49 +0x49 fp=0xc00006bdb8 sp=0xc00006bd78 pc=0x7a4849
os/user.Current.func1()
	/usr/local/go/src/os/user/lookup.go:15 +0x25 fp=0xc00006bde0 sp=0xc00006bdb8 pc=0x7a5985
sync.(*Once).doSlow(0x2f9ed80, 0x214c128)
	/usr/local/go/src/sync/once.go:66 +0xec fp=0xc00006be30 sp=0xc00006bde0 pc=0x4863cc
sync.(*Once).Do(...)
	/usr/local/go/src/sync/once.go:57
os/user.Current(0xc000042380, 0xa, 0x20874b5)
	/usr/local/go/src/os/user/lookup.go:15 +0x105 fp=0xc00006be60 sp=0xc00006be30 pc=0x7a4265
k8s.io/klog.init.1()
	/go/src/github.com/coreos/flannel/vendor/k8s.io/klog/klog_file.go:58 +0x45 fp=0xc00006bec8 sp=0xc00006be60 pc=0x7aa585
runtime.doInit(0x2f40280)
	/usr/local/go/src/runtime/proc.go:5646 +0x8a fp=0xc00006bef8 sp=0xc00006bec8 pc=0x44760a
runtime.doInit(0x2f3a760)
	/usr/local/go/src/runtime/proc.go:5641 +0x57 fp=0xc00006bf28 sp=0xc00006bef8 pc=0x4475d7
runtime.doInit(0x2f36f40)
	/usr/local/go/src/runtime/proc.go:5641 +0x57 fp=0xc00006bf58 sp=0xc00006bf28 pc=0x4475d7
runtime.doInit(0x2f44220)
	/usr/local/go/src/runtime/proc.go:5641 +0x57 fp=0xc00006bf88 sp=0xc00006bf58 pc=0x4475d7
runtime.main()
	/usr/local/go/src/runtime/proc.go:191 +0x1c5 fp=0xc00006bfe0 sp=0xc00006bf88 pc=0x43a405
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc00006bfe8 sp=0xc00006bfe0 pc=0x46d481

goroutine 6 [chan receive]:
k8s.io/klog.(*loggingT).flushDaemon(0x2f9fbe0)
	/go/src/github.com/coreos/flannel/vendor/k8s.io/klog/klog.go:1010 +0x8b
created by k8s.io/klog.init.0
	/go/src/github.com/coreos/flannel/vendor/k8s.io/klog/klog.go:411 +0xd8
[root@stream8-40 ~]# uname -r  ;cat /etc/redhat-release
4.18.0-277.el8.x86_64
CentOS Stream release 8
[root@stream8-40 ~]#

`

**Comment by szbjb** [comment]
> 你下的是rc的版本吗，是release的话换12的试试

`


[root@stream8-40 ~]# ll
total 66328
-rw-------. 1 root root     1380 Mar  8 09:56 anaconda-ks.cfg
-rwxr-xr-x. 1 1000 1000 45687144 Feb  9 04:42 flanneld
-rw-r--r--. 1 root root  9565406 Mar 18 14:41 flannel-v0.12.0-linux-amd64.tar.gz
-rw-r--r--. 1 root root 12638789 Mar 18 14:30 flannel-v0.13.1-rc2-linux-amd64.tar.gz
-rwxrwxrwx. 1 root root      440 Mar  8 09:59 ip.sh
-rwxr-xr-x. 1 1000 1000     2139 May 29  2019 mk-docker-opts.sh
-rw-rw-r--. 1 1000 1000     4642 Feb  9 04:29 README.md
[root@stream8-40 ~]# md5sum  flanneld
ecd7b08f48c38e95305fab35f5b9f2e8  flanneld
[root@stream8-40 ~]# md5sum  flannel-v0.12.0-linux-amd64.tar.gz
632b8b3c97c82a16f07ac143df960502  flannel-v0.12.0-linux-amd64.tar.gz
[root@stream8-40 ~]# ./flanneld  -version
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xe5 pc=0x7f0f78a080f1]

runtime stack:
runtime.throw(0x20c058e, 0x2a)
	/usr/local/go/src/runtime/panic.go:1116 +0x72
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:726 +0x4ac

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x1a4d360, 0xc00006bbd0, 0xc000010030)
	/usr/local/go/src/runtime/cgocall.go:133 +0x5b fp=0xc00006bba0 sp=0xc00006bb68 pc=0x40571b
os/user._Cfunc_mygetpwuid_r(0x0, 0xc000098db0, 0x3b950b0, 0x400, 0xc000010030, 0x7f0f00000000)
	_cgo_gotypes.go:175 +0x4d fp=0xc00006bbd0 sp=0xc00006bba0 pc=0x7a456d
os/user.lookupUnixUid.func1.1(0x0, 0xc000098db0, 0xc000048c70, 0xc000010030, 0xc00006bc70)
	/usr/local/go/src/os/user/cgo_lookup_unix.go:103 +0xd0 fp=0xc00006bc20 sp=0xc00006bbd0 pc=0x7a5ad0
os/user.lookupUnixUid.func1(0x1e049a0)
	/usr/local/go/src/os/user/cgo_lookup_unix.go:103 +0x45 fp=0xc00006bc58 sp=0xc00006bc20 pc=0x7a5b45
os/user.retryWithBuffer(0xc000048c70, 0xc00006bd30, 0x0, 0x0)
	/usr/local/go/src/os/user/cgo_lookup_unix.go:247 +0x3e fp=0xc00006bcb0 sp=0xc00006bc58 pc=0x7a509e
os/user.lookupUnixUid(0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/os/user/cgo_lookup_unix.go:96 +0x132 fp=0xc00006bd78 sp=0xc00006bcb0 pc=0x7a49b2
os/user.current(0x0, 0x0, 0x0)
	/usr/local/go/src/os/user/cgo_lookup_unix.go:49 +0x49 fp=0xc00006bdb8 sp=0xc00006bd78 pc=0x7a4849
os/user.Current.func1()
	/usr/local/go/src/os/user/lookup.go:15 +0x25 fp=0xc00006bde0 sp=0xc00006bdb8 pc=0x7a5985
sync.(*Once).doSlow(0x2f9ed80, 0x214c128)
	/usr/local/go/src/sync/once.go:66 +0xec fp=0xc00006be30 sp=0xc00006bde0 pc=0x4863cc
sync.(*Once).Do(...)
	/usr/local/go/src/sync/once.go:57
os/user.Current(0xc000042390, 0xa, 0x20874b5)
	/usr/local/go/src/os/user/lookup.go:15 +0x105 fp=0xc00006be60 sp=0xc00006be30 pc=0x7a4265
k8s.io/klog.init.1()
	/go/src/github.com/coreos/flannel/vendor/k8s.io/klog/klog_file.go:58 +0x45 fp=0xc00006bec8 sp=0xc00006be60 pc=0x7aa585
runtime.doInit(0x2f40280)
	/usr/local/go/src/runtime/proc.go:5646 +0x8a fp=0xc00006bef8 sp=0xc00006bec8 pc=0x44760a
runtime.doInit(0x2f3a760)
	/usr/local/go/src/runtime/proc.go:5641 +0x57 fp=0xc00006bf28 sp=0xc00006bef8 pc=0x4475d7
runtime.doInit(0x2f36f40)
	/usr/local/go/src/runtime/proc.go:5641 +0x57 fp=0xc00006bf58 sp=0xc00006bf28 pc=0x4475d7
runtime.doInit(0x2f44220)
	/usr/local/go/src/runtime/proc.go:5641 +0x57 fp=0xc00006bf88 sp=0xc00006bf58 pc=0x4475d7
runtime.main()
	/usr/local/go/src/runtime/proc.go:191 +0x1c5 fp=0xc00006bfe0 sp=0xc00006bf88 pc=0x43a405
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc00006bfe8 sp=0xc00006bfe0 pc=0x46d481

goroutine 6 [chan receive]:
k8s.io/klog.(*loggingT).flushDaemon(0x2f9fbe0)
	/go/src/github.com/coreos/flannel/vendor/k8s.io/klog/klog.go:1010 +0x8b
created by k8s.io/klog.init.0
	/go/src/github.com/coreos/flannel/vendor/k8s.io/klog/klog.go:411 +0xd8
[root@stream8-40 ~]# cat /etc/redhat-release ;uname -r
CentOS Stream release 8
4.18.0-277.el8.x86_64


`

**Comment by zhangguanzhang** [comment]
```
[root@Centos8 ~/flannel]# ./flanneld --version
v0.13.1-rc2
[root@Centos8 ~/flannel]# cat /etc/os-release 
NAME="CentOS Linux"
VERSION="8 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="8"

```

**Comment by szbjb** [comment]
***@***.*** ~]# cat /etc/os-release
NAME="CentOS Stream"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Stream 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"
***@***.*** ~]#





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "flannel-io/flannel"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月19日(星期五) 上午9:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [flannel-io/flannel] fatal error: unexpected signal during runtime execution [signal SIGSEGV: segmentation violation code=0x1 addr=0xe5 pc=0x7f67d0cca0f1] (#1418)





 [root@Centos8 ~/flannel]# ./flanneld --version v0.13.1-rc2 [root@Centos8 ~/flannel]# cat /etc/os-release  NAME="CentOS Linux" VERSION="8 (Core)" ID="centos" ID_LIKE="rhel fedora" VERSION_ID="8" PLATFORM_ID="platform:el8" PRETTY_NAME="CentOS Linux 8 (Core)" ANSI_COLOR="0;31" CPE_NAME="cpe:/o:centos:centos:8" HOME_URL="https://www.centos.org/" BUG_REPORT_URL="https://bugs.centos.org/" CENTOS_MANTISBT_PROJECT="CentOS-8" CENTOS_MANTISBT_PROJECT_VERSION="8" REDHAT_SUPPORT_PRODUCT="centos" REDHAT_SUPPORT_PRODUCT_VERSION="8"

**Comment by manfredlift** [comment]
I am getting the same panic with flannel versions v0.11, v0.13 and v0.14-rc1.

```
$ cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="8.3 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.3"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.3 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.3:GA"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.3
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.3"
```

I noticed that downgrading glibc fixes the issue. It works on `glibc-2.28-127.el8_3.2`, but doesn't work on the latest `glibc-2.28-151.el8`. Also the following issue has similar panics for a static golang build: https://github.com/golang/go/issues/24787

**Comment by kkallday** [comment]
+1

```
NAME="Ubuntu"
VERSION="21.04 (Hirsute Hippo)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 21.04"
VERSION_ID="21.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute

```

**Comment by cucker0** [comment]
## you can rebuild flannel on CentOS 8.
I have build a docker image for build flannel.

## How to use this image
1. clone flannel repository.
2. pull  image and tag this image to the `Makefile` require.
3. make flanneld

* For example
    ```bash
    git clone --branch v0.14.0 https://github.com/flannel-io/flannel.git
    docker pull cucker/golang
    docker tag cucker/golang golang:$(grep "^GO_VERSION=" Makefile |awk -F "=" '{print $2}')
    make dist/flanneld
    ```

    ```bash
    $ ./dist/flanneld -version
    v0.14.0
    
    $cat /etc/redhat-release 
    CentOS Linux release 8.4.2105
    
    $ cat /etc/os-release 
    NAME="CentOS Linux"
    VERSION="8"
    ID="centos"
    ID_LIKE="rhel fedora"
    VERSION_ID="8"
    PLATFORM_ID="platform:el8"
    PRETTY_NAME="CentOS Linux 8"
    ANSI_COLOR="0;31"
    CPE_NAME="cpe:/o:centos:centos:8"
    HOME_URL="https://centos.org/"
    BUG_REPORT_URL="https://bugs.centos.org/"
    CENTOS_MANTISBT_PROJECT="CentOS-8"
    CENTOS_MANTISBT_PROJECT_VERSION="8"
    ```

**Comment by Lucky-dj** [comment]
> ## Rebuild flannel on CentOS 8
> I have build a docker image for build flannel.
> 
> ## How to use this image
> 1. clone flannel repository.
> 2. pull  `cucker/golang` image and tag this image to the `./Makefile` require.
>    The `v1.14.0` tag Makefile define `golang:1.15.5`  image  for build environment to run.
> 3. make flanneld
> 
> * For example
>   ```shell
>   git clone --branch v0.14.0 https://github.com/flannel-io/flannel.git
>   cd flannel
>   docker pull cucker/golang
>   docker tag cucker/golang golang:$(grep "^GO_VERSION=" Makefile |awk -F "=" '{print $2}')
>   make dist/flanneld  # It will running a container to build with golang image
>   ```
>   
>   
>       
>         
>       
>   
>         
>       
>   
>       
>     
>   ```shell
>   $ ./dist/flanneld -version
>   v0.14.0
>   
>   $cat /etc/redhat-release 
>   CentOS Linux release 8.4.2105
>   
>   $ cat /etc/os-release 
>   NAME="CentOS Linux"
>   VERSION="8"
>   ID="centos"
>   ID_LIKE="rhel fedora"
>   VERSION_ID="8"
>   PLATFORM_ID="platform:el8"
>   PRETTY_NAME="CentOS Linux 8"
>   ANSI_COLOR="0;31"
>   CPE_NAME="cpe:/o:centos:centos:8"
>   HOME_URL="https://centos.org/"
>   BUG_REPORT_URL="https://bugs.centos.org/"
>   CENTOS_MANTISBT_PROJECT="CentOS-8"
>   CENTOS_MANTISBT_PROJECT_VERSION="8"
>   ```
> 
> ## There are binary files
> * [flannel_v0.14.0](https://github.com/cucker0/docker/tree/main/resources/flannel/flannel_v0.14.0)
> * [flannel_v0.13.0](https://github.com/cucker0/docker/tree/main/resources/flannel/flannel_v0.13.0)
> 
> ## The release v0.9.1 running OK on CentOS 8

v0.9.1 nice
