### ISSUE TITLE
Flannel is sometimes missing connections to peers

### ISSUE THREAD

**Issue by lsorense** [flannel-io/flannel#1531]
## Expected Behavior

I would expect flannel to correctly connect to the other nodes on the network.  Sometimes it is missing some of the connections.

## Current Behavior

Sometimes flannel isn't adding a connection to a peer causing pods to be unable to communicate.  Restarting flannel usually fixes it.

## Possible Solution

If I had a better idea how to debug what it is doing I might be able to fix it.

## Steps to Reproduce (for bugs)

Setup new k8s cluster with multiple nodes and flannel networking.   Sometimes nodes are unable to communicate.  Seems to happen most often on initial deployment, but sometimes a node reboot can hit it too. It feels like a race condition in flannel.  I grabbed a log from one case where a node had a route to one of the other nodes but was missing the 3rd node, even though the log said it was adding an entry for the 3rd node too, but it was not present in the routing table.  Restarting flannel resulted in all the entries being in the routing table as expected.

## Context

I was trying to setup a 3 node k8s cluster with flannel networking.  In some cases pods are unable to resolve dns queries because they can't reach other pods, including kube-dns.

## Your Environment

* Flannel version:
flannel --version says v1.0.0
docker image is v0.15.1 since none of the commits since appeared relevant
* Backend used (e.g. vxlan or udp):
Tried vxlan initially, then tried DirectRouting which makes it easier to see when entries are missing since routing table enties are not present.  When I had vxlan in use, tcpdump showed that the node never even attempted to send any vxlan packets to any other node when the problem was present.  Restarting flannel usually made vxlan packets appear and solved the problem.  The logs never appear to show any indication that there is any problem.

* Etcd version:
3.4.13
* Kubernetes version (if used):
1.20.4
* Operating System and version:
Yocto 3.0
* Link to your project (optional):

Routing table when broken:
default via 10.48.47.1 dev eth1.4007 proto zebra
10.48.4.0/24 dev eth0 proto kernel scope link src 10.48.4.33
10.48.47.0/24 dev eth1.4007 proto kernel scope link src 10.48.47.36
10.96.1.0/24 dev cni0 proto kernel scope link src 10.96.1.1
10.96.2.0/24 via 10.48.4.32 dev eth0
172.17.0.0/24 dev docker0 proto kernel scope link src 172.17.0.1 linkdown
172.31.0.16/28 dev tap0 proto kernel scope link src 172.31.0.17 linkdown

Routing table after restart:
default via 10.48.47.1 dev eth1.4007 proto zebra
10.48.4.0/24 dev eth0 proto kernel scope link src 10.48.4.33
10.48.47.0/24 dev eth1.4007 proto kernel scope link src 10.48.47.36
10.96.0.0/24 via 10.48.4.31 dev eth0
10.96.1.0/24 dev cni0 proto kernel scope link src 10.96.1.1
10.96.2.0/24 via 10.48.4.32 dev eth0
172.17.0.0/24 dev docker0 proto kernel scope link src 172.17.0.1 linkdown
172.31.0.16/28 dev tap0 proto kernel scope link src 172.31.0.17 linkdown

Log from flannel when in broken state, along with backtrace when restarting:
I0126 21:14:18.624873       1 main.go:217] CLI flags config: {etcdEndpoints:http://127.0.0.1:4001,http://127.0.0.1:2379 etcdPrefix:/coreos.com/network etcdKeyfile: etcdCertfile: etcdCAFile: etcdUsername: etcdPassword: help:false version:false autoDetectIPv4:false autoDetectIPv6:false kubeSubnetMgr:true kubeApiUrl: kubeAnnotationPrefix:flannel.alpha.coreos.com kubeConfigFile: iface:[eth0] ifaceRegex:[] ipMasq:true subnetFile:/run/flannel/subnet.env subnetDir: publicIP: publicIPv6: subnetLeaseRenewMargin:60 healthzIP:0.0.0.0 healthzPort:0 charonExecutablePath: charonViciUri: iptablesResyncSeconds:5 iptablesForwardRules:true netConfPath:/etc/kube-flannel/net-conf.json setNodeNetworkUnavailable:true}
W0126 21:14:18.625258       1 client_config.go:608] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0126 21:14:18.822583       1 kube.go:120] Waiting 10m0s for node controller to sync
I0126 21:14:18.822685       1 kube.go:378] Starting kube subnet manager
I0126 21:14:19.822745       1 kube.go:127] Node controller sync successful
I0126 21:14:19.822777       1 main.go:237] Created subnet manager: Kubernetes Subnet Manager - c2-xca3.pinewoods.tor.lab.local
I0126 21:14:19.822786       1 main.go:240] Installing signal handlers
I0126 21:14:19.920065       1 main.go:459] Found network config - Backend type: vxlan
I0126 21:14:19.920600       1 main.go:698] Using interface with name eth0 and address 10.48.4.33
I0126 21:14:19.920620       1 main.go:720] Defaulting external address to interface address (10.48.4.33)
I0126 21:14:19.920625       1 main.go:733] Defaulting external v6 address to interface address (<nil>)
I0126 21:14:19.920699       1 vxlan.go:137] VXLAN config: VNI=1 Port=0 GBP=false Learning=false DirectRouting=true
I0126 21:14:20.022118       1 kube.go:339] Setting NodeNetworkUnavailable
I0126 21:14:20.030418       1 main.go:408] Current network or subnet (10.96.0.0/16, 10.96.1.0/24) is not equal to previous one (0.0.0.0/0, 0.0.0.0/0), trying to recycle old iptables rules
I0126 21:14:20.428658       1 iptables.go:240] Deleting iptables rule: -s 0.0.0.0/0 -d 0.0.0.0/0 -j RETURN
I0126 21:14:20.429780       1 iptables.go:240] Deleting iptables rule: -s 0.0.0.0/0 ! -d 224.0.0.0/4 -j MASQUERADE --random-fully
I0126 21:14:20.430996       1 iptables.go:240] Deleting iptables rule: ! -s 0.0.0.0/0 -d 0.0.0.0/0 -j RETURN
I0126 21:14:20.431855       1 iptables.go:240] Deleting iptables rule: ! -s 0.0.0.0/0 -d 0.0.0.0/0 -j MASQUERADE --random-fully
I0126 21:14:20.432824       1 main.go:340] Setting up masking rules
I0126 21:14:20.433438       1 main.go:361] Changing default FORWARD chain policy to ACCEPT
I0126 21:14:20.433533       1 main.go:374] Wrote subnet file to /run/flannel/subnet.env
I0126 21:14:20.433543       1 main.go:378] Running backend.
I0126 21:14:20.433560       1 main.go:396] Waiting for all goroutines to exit
I0126 21:14:20.433596       1 vxlan_network.go:60] watching for new subnet leases
I0126 21:14:20.434270       1 vxlan_network.go:172] Adding direct route to subnet: 10.96.0.0/24 PublicIP: 10.48.4.31
I0126 21:14:20.520811       1 iptables.go:216] Some iptables rules are missing; deleting and recreating rules
I0126 21:14:20.520828       1 iptables.go:240] Deleting iptables rule: -s 10.96.0.0/16 -d 10.96.0.0/16 -j RETURN
I0126 21:14:20.521167       1 iptables.go:216] Some iptables rules are missing; deleting and recreating rules
I0126 21:14:20.521184       1 iptables.go:240] Deleting iptables rule: -s 10.96.0.0/16 -j ACCEPT
I0126 21:14:20.521671       1 iptables.go:240] Deleting iptables rule: -s 10.96.0.0/16 ! -d 224.0.0.0/4 -j MASQUERADE --random-fully
I0126 21:14:20.522030       1 iptables.go:240] Deleting iptables rule: -d 10.96.0.0/16 -j ACCEPT
I0126 21:14:20.522605       1 iptables.go:240] Deleting iptables rule: ! -s 10.96.0.0/16 -d 10.96.1.0/24 -j RETURN
I0126 21:14:20.523499       1 iptables.go:240] Deleting iptables rule: ! -s 10.96.0.0/16 -d 10.96.0.0/16 -j MASQUERADE --random-fully
I0126 21:14:20.524360       1 iptables.go:228] Adding iptables rule: -s 10.96.0.0/16 -d 10.96.0.0/16 -j RETURN
I0126 21:14:20.522871       1 iptables.go:228] Adding iptables rule: -s 10.96.0.0/16 -j ACCEPT
I0126 21:14:20.621237       1 iptables.go:228] Adding iptables rule: -s 10.96.0.0/16 ! -d 224.0.0.0/4 -j MASQUERADE --random-fully
I0126 21:14:20.622390       1 iptables.go:228] Adding iptables rule: -d 10.96.0.0/16 -j ACCEPT
I0126 21:14:20.623078       1 iptables.go:228] Adding iptables rule: ! -s 10.96.0.0/16 -d 10.96.1.0/24 -j RETURN
I0126 21:14:20.721425       1 iptables.go:228] Adding iptables rule: ! -s 10.96.0.0/16 -d 10.96.0.0/16 -j MASQUERADE --random-fully
I0126 21:15:54.337732       1 vxlan_network.go:172] Adding direct route to subnet: 10.96.2.0/24 PublicIP: 10.48.4.32
SIGQUIT: quit
PC=0x46f301 m=0 sigcode=0

goroutine 0 [idle]:
runtime.futex(0x3338f08, 0x80, 0x0, 0x0, 0x7ffe00000000, 0x46eedc, 0x1639, 0x1dd1f8c4, 0x7ffe8c5d1378, 0x40dd7f, ...)
        /usr/local/go/src/runtime/sys_linux_amd64.s:587 +0x21
runtime.futexsleep(0x3338f08, 0x100000000, 0xffffffffffffffff)
        /usr/local/go/src/runtime/os_linux.go:45 +0x46
runtime.notesleep(0x3338f08)
        /usr/local/go/src/runtime/lock_futex.go:159 +0x9f
runtime.stopm()
        /usr/local/go/src/runtime/proc.go:1918 +0xc5
runtime.findrunnable(0xc000056800, 0x0)
        /usr/local/go/src/runtime/proc.go:2479 +0xa7f
runtime.schedule()
        /usr/local/go/src/runtime/proc.go:2677 +0x2d7
runtime.park_m(0xc000415380)
        /usr/local/go/src/runtime/proc.go:2845 +0x9d
runtime.mcall(0x1b6a080)
        /usr/local/go/src/runtime/asm_amd64.s:318 +0x5b

goroutine 1 [semacquire, 87 minutes]:
sync.runtime_Semacquire(0xc0004118a8)
        /usr/local/go/src/runtime/sema.go:56 +0x45
sync.(*WaitGroup).Wait(0xc0004118a0)
        /usr/local/go/src/sync/waitgroup.go:130 +0x65
main.main()
        /go/src/github.com/flannel-io/flannel/main.go:398 +0xbb8

goroutine 6 [chan receive]:
k8s.io/klog.(*loggingT).flushDaemon(0x3337ec0)
        /go/src/github.com/flannel-io/flannel/vendor/k8s.io/klog/klog.go:1010 +0x8b
created by k8s.io/klog.init.0
        /go/src/github.com/flannel-io/flannel/vendor/k8s.io/klog/klog.go:411 +0xd8

goroutine 8 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x3337fa0)
        /go/src/github.com/flannel-io/flannel/vendor/k8s.io/klog/v2/klog.go:1131 +0x8b
created by k8s.io/klog/v2.init.0
        /go/src/github.com/flannel-io/flannel/vendor/k8s.io/klog/v2/klog.go:416 +0xd8

goroutine 98 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc00078c230)
        /go/src/github.com/flannel-io/flannel/vendor/go.opencensus.io/stats/view/worker.go:154 +0x105
created by go.opencensus.io/stats/view.init.0
        /go/src/github.com/flannel-io/flannel/vendor/go.opencensus.io/stats/view/worker.go:32 +0x57

goroutine 87 [IO wait]:
internal/poll.runtime_pollWait(0x7f77fa2d2c58, 0x72, 0x2478080)
        /usr/local/go/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc0007be198, 0x72, 0x2478000, 0x32c8288, 0x0)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0007be180, 0xc0009a2000, 0xc3f2, 0xc3f2, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:159 +0x1a5
net.(*netFD).Read(0xc0007be180, 0xc0009a2000, 0xc3f2, 0xc3f2, 0x203000, 0x635d7b, 0xc0004fd2e0)
        /usr/local/go/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc000114198, 0xc0009a2000, 0xc3f2, 0xc3f2, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:182 +0x8e
crypto/tls.(*atLeastReader).Read(0xc00031c740, 0xc0009a2000, 0xc3f2, 0xc3f2, 0x1a4, 0xc3ed, 0xc000555710)
        /usr/local/go/src/crypto/tls/conn.go:779 +0x62
bytes.(*Buffer).ReadFrom(0xc0004fd400, 0x2472940, 0xc00031c740, 0x40d265, 0x1ec8400, 0x2160980)
        /usr/local/go/src/bytes/buffer.go:204 +0xb1
crypto/tls.(*Conn).readFromUntil(0xc0004fd180, 0x2476700, 0xc000114198, 0x5, 0xc000114198, 0x193)
        /usr/local/go/src/crypto/tls/conn.go:801 +0xf3
crypto/tls.(*Conn).readRecordOrCCS(0xc0004fd180, 0x0, 0x0, 0x203000)
        /usr/local/go/src/crypto/tls/conn.go:608 +0x115
crypto/tls.(*Conn).readRecord(...)
        /usr/local/go/src/crypto/tls/conn.go:576
crypto/tls.(*Conn).Read(0xc0004fd180, 0xc0004a7000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:1252 +0x15f
bufio.(*Reader).Read(0xc0004667e0, 0xc000964498, 0x9, 0x9, 0x483f3c, 0xc0003b3900, 0x18a)
        /usr/local/go/src/bufio/bufio.go:227 +0x222
io.ReadAtLeast(0x24727c0, 0xc0004667e0, 0xc000964498, 0x9, 0x9, 0x9, 0xc0003b38f0, 0x22df6c0, 0xc0003b38e8)
        /usr/local/go/src/io/io.go:314 +0x87
io.ReadFull(...)
        /usr/local/go/src/io/io.go:333
golang.org/x/net/http2.readFrameHeader(0xc000964498, 0x9, 0x9, 0x24727c0, 0xc0004667e0, 0x0, 0x0, 0xc000555dd0, 0x46a5a5)
        /go/src/github.com/flannel-io/flannel/vendor/golang.org/x/net/http2/frame.go:237 +0x89
golang.org/x/net/http2.(*Framer).ReadFrame(0xc000964460, 0xc00078abd0, 0x0, 0x0, 0x0)
        /go/src/github.com/flannel-io/flannel/vendor/golang.org/x/net/http2/frame.go:492 +0xa5
golang.org/x/net/http2.(*clientConnReadLoop).run(0xc000555fa8, 0x0, 0x0)
        /go/src/github.com/flannel-io/flannel/vendor/golang.org/x/net/http2/transport.go:1819 +0xd8
golang.org/x/net/http2.(*ClientConn).readLoop(0xc000103e00)
        /go/src/github.com/flannel-io/flannel/vendor/golang.org/x/net/http2/transport.go:1741 +0x6f
created by golang.org/x/net/http2.(*Transport).newClientConn
        /go/src/github.com/flannel-io/flannel/vendor/golang.org/x/net/http2/transport.go:705 +0x6c5

goroutine 47 [sync.Cond.Wait]:
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:312
sync.runtime_notifyListWait(0xc000184a28, 0x59)
        /usr/local/go/src/runtime/sema.go:513 +0xf8
sync.(*Cond).Wait(0xc000184a18)
        /usr/local/go/src/sync/cond.go:56 +0x9d
k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop(0xc000184a00, 0xc000503a40, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/flannel-io/flannel/vendor/k8s.io/client-go/tools/cache/delta_fifo.go:488 +0x98
k8s.io/client-go/tools/cache.(*controller).processLoop(0xc000014090)
        /go/src/github.com/flannel-io/flannel/vendor/k8s.io/client-go/tools/cache/controller.go:179 +0x42
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00016ff40)
        /go/src/github.com/flannel-io/flannel/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000559f40, 0x24762c0, 0xc000503a70, 0xc00020a201, 0x0)
        /go/src/github.com/flannel-io/flannel/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xad
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00016ff40, 0x3b9aca00, 0x0, 0xc00040c001, 0x0)
        /go/src/github.com/flannel-io/flannel/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(...)
        /go/src/github.com/flannel-io/flannel/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*controller).Run(0xc000014090, 0x0)
        /go/src/github.com/flannel-io/flannel/vendor/k8s.io/client-go/tools/cache/controller.go:150 +0x2ce
github.com/flannel-io/flannel/subnet/kube.(*kubeSubnetManager).Run(0xc000964620, 0x24b1e40, 0xc000046018)
        /go/src/github.com/flannel-io/flannel/subnet/kube/kube.go:379 +0x90
created by github.com/flannel-io/flannel/subnet/kube.NewSubnetManager
        /go/src/github.com/flannel-io/flannel/subnet/kube/kube.go:118 +0x53d

goroutine 117 [syscall, 87 minutes]:
os/signal.signal_recv(0xc00079a300)
        /usr/local/go/src/runtime/sigqueue.go:147 +0x9d
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:23 +0x25
created by os/signal.Notify.func1.1
        /usr/local/go/src/os/signal/signal.go:150 +0x45

goroutine 49 [chan receive (nil chan), 87 minutes]:
k8s.io/client-go/tools/cache.(*controller).Run.func1(0x0, 0xc000014090)
        /go/src/github.com/flannel-io/flannel/vendor/k8s.io/client-go/tools/cache/controller.go:127 +0x34
created by k8s.io/client-go/tools/cache.(*controller).Run
        /go/src/github.com/flannel-io/flannel/vendor/k8s.io/client-go/tools/cache/controller.go:126 +0xa5

goroutine 114 [select]:
k8s.io/client-go/tools/cache.(*Reflector).watchHandler(0xc0001c4750, 0xc07490f1c7ee2d48, 0x45564dbce6a, 0x3337ac0, 0x2487040, 0xc000146ac0, 0xc000019b88, 0xc0000e12c0, 0x0, 0x0, ...)
        /go/src/github.com/flannel-io/flannel/vendor/k8s.io/client-go/tools/cache/reflector.go:451 +0x1a5
k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch(0xc0001c4750, 0x0, 0x0, 0x0)
        /go/src/github.com/flannel-io/flannel/vendor/k8s.io/client-go/tools/cache/reflector.go:415 +0x657
k8s.io/client-go/tools/cache.(*Reflector).Run.func1()
        /go/src/github.com/flannel-io/flannel/vendor/k8s.io/client-go/tools/cache/reflector.go:209 +0x38
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000223ee0)
        /go/src/github.com/flannel-io/flannel/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000019ee0, 0x24762a0, 0xc0004081e0, 0x1, 0x0)
        /go/src/github.com/flannel-io/flannel/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xad
k8s.io/client-go/tools/cache.(*Reflector).Run(0xc0001c4750, 0x0)
        /go/src/github.com/flannel-io/flannel/vendor/k8s.io/client-go/tools/cache/reflector.go:208 +0x196
k8s.io/apimachinery/pkg/util/wait.(*Group).StartWithChannel.func1()
        /go/src/github.com/flannel-io/flannel/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:56 +0x2e
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc00020a220, 0xc0004f6800)
        /go/src/github.com/flannel-io/flannel/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:73 +0x51
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
        /go/src/github.com/flannel-io/flannel/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x65

goroutine 116 [select, 2 minutes]:
k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch.func2(0xc0001c4750, 0x0, 0xc00079a000, 0xc0000e12c0)
        /go/src/github.com/flannel-io/flannel/vendor/k8s.io/client-go/tools/cache/reflector.go:361 +0x16f
created by k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch
        /go/src/github.com/flannel-io/flannel/vendor/k8s.io/client-go/tools/cache/reflector.go:355 +0x2a5

goroutine 118 [select, 87 minutes]:
main.shutdownHandler(0x24b1e00, 0xc000789040, 0xc0007a2300, 0xc00092d760)
        /go/src/github.com/flannel-io/flannel/main.go:437 +0xc5
main.main.func1(0x24b1e00, 0xc000789040, 0xc0007a2300, 0xc00092d760, 0xc0004118a0)
        /go/src/github.com/flannel-io/flannel/main.go:248 +0x49
created by main.main
        /go/src/github.com/flannel-io/flannel/main.go:247 +0x451

goroutine 119 [chan receive, 87 minutes]:
github.com/flannel-io/flannel/backend.(*manager).GetBackend.func1(0xc0004086e0, 0xc000818c60, 0x5)
        /go/src/github.com/flannel-io/flannel/backend/manager.go:74 +0x4e
created by github.com/flannel-io/flannel/backend.(*manager).GetBackend
        /go/src/github.com/flannel-io/flannel/backend/manager.go:73 +0x235

goroutine 132 [sleep]:
time.Sleep(0x12a05f200)
        /usr/local/go/src/runtime/time.go:188 +0xbf
github.com/flannel-io/flannel/network.SetupAndEnsureIPTables(0xc0009121c0, 0x4, 0x4, 0x5)
        /go/src/github.com/flannel-io/flannel/network/iptables.go:155 +0xcd
created by main.main
        /go/src/github.com/flannel-io/flannel/main.go:341 +0x1247

goroutine 133 [sleep]:
time.Sleep(0x12a05f200)
        /usr/local/go/src/runtime/time.go:188 +0xbf
github.com/flannel-io/flannel/network.SetupAndEnsureIPTables(0xc0001b2d20, 0x2, 0x2, 0x5)
        /go/src/github.com/flannel-io/flannel/network/iptables.go:155 +0xcd
created by main.main
        /go/src/github.com/flannel-io/flannel/main.go:362 +0xec5

goroutine 134 [chan receive, 87 minutes]:
github.com/flannel-io/flannel/backend/vxlan.(*network).Run(0xc0003cb050, 0x24b1e00, 0xc000789040)
        /go/src/github.com/flannel-io/flannel/backend/vxlan/vxlan_network.go:73 +0x18f
main.main.func2(0x249f980, 0xc0003cb050, 0x24b1e00, 0xc000789040, 0xc0004118a0)
        /go/src/github.com/flannel-io/flannel/main.go:381 +0x45
created by main.main
        /go/src/github.com/flannel-io/flannel/main.go:380 +0xb12

goroutine 135 [select, 87 minutes]:
github.com/flannel-io/flannel/subnet/kube.(*kubeSubnetManager).WatchLeases(0xc000964620, 0x24b1e00, 0xc000789040, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/flannel-io/flannel/subnet/kube/kube.go:367 +0x13a
github.com/flannel-io/flannel/subnet.WatchLeases(0x24b1e00, 0xc000789040, 0x24c2080, 0xc000964620, 0xc0001e0320, 0xc0000e21e0)
        /go/src/github.com/flannel-io/flannel/subnet/watch.go:36 +0xbb
github.com/flannel-io/flannel/backend/vxlan.(*network).Run.func1(0x24b1e00, 0xc000789040, 0xc0003cb050, 0xc0000e21e0, 0xc00082e5c0)
        /go/src/github.com/flannel-io/flannel/backend/vxlan/vxlan_network.go:64 +0x65
created by github.com/flannel-io/flannel/backend/vxlan.(*network).Run
        /go/src/github.com/flannel-io/flannel/backend/vxlan/vxlan_network.go:63 +0x11d

goroutine 6049 [select, 9 minutes]:
golang.org/x/net/http2.awaitRequestCancel(0xc00021c400, 0xc0000e29c0, 0xc0003c2480, 0xc0003c4720)
        /go/src/github.com/flannel-io/flannel/vendor/golang.org/x/net/http2/transport.go:318 +0x125
golang.org/x/net/http2.(*clientStream).awaitRequestCancel(0xc0003b38c0, 0xc00021c400)
        /go/src/github.com/flannel-io/flannel/vendor/golang.org/x/net/http2/transport.go:344 +0x45
created by golang.org/x/net/http2.(*clientConnReadLoop).handleResponse
        /go/src/github.com/flannel-io/flannel/vendor/golang.org/x/net/http2/transport.go:2054 +0x768

goroutine 6066 [sync.Cond.Wait]:
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:312
sync.runtime_notifyListWait(0xc0003b3900, 0xb)
        /usr/local/go/src/runtime/sema.go:513 +0xf8
sync.(*Cond).Wait(0xc0003b38f0)
        /usr/local/go/src/sync/cond.go:56 +0x9d
golang.org/x/net/http2.(*pipe).Read(0xc0003b38e8, 0xc000036001, 0x3dff, 0x3dff, 0x0, 0x0, 0x0)
        /go/src/github.com/flannel-io/flannel/vendor/golang.org/x/net/http2/pipe.go:65 +0x97
golang.org/x/net/http2.transportResponseBody.Read(0xc0003b38c0, 0xc000036001, 0x3dff, 0x3dff, 0x0, 0x0, 0x0)
        /go/src/github.com/flannel-io/flannel/vendor/golang.org/x/net/http2/transport.go:2108 +0xaf
encoding/json.(*Decoder).refill(0xc0003b3b80, 0xa, 0x9)
        /usr/local/go/src/encoding/json/stream.go:165 +0xeb
encoding/json.(*Decoder).readValue(0xc0003b3b80, 0x0, 0x0, 0x1e68f60)
        /usr/local/go/src/encoding/json/stream.go:140 +0x1ff
encoding/json.(*Decoder).Decode(0xc0003b3b80, 0x1eb3f80, 0xc00031c7a0, 0x0, 0x0)
        /usr/local/go/src/encoding/json/stream.go:63 +0x79
k8s.io/apimachinery/pkg/util/framer.(*jsonFrameReader).Read(0xc000203860, 0xc000642000, 0x4000, 0x4a80, 0xc00055bde0, 0x7f77f9275480, 0x38)
        /go/src/github.com/flannel-io/flannel/vendor/k8s.io/apimachinery/pkg/util/framer/framer.go:150 +0x1a8
k8s.io/apimachinery/pkg/runtime/serializer/streaming.(*decoder).Decode(0xc000112eb0, 0x0, 0x2486c80, 0xc0004b4900, 0x0, 0x0, 0x462160, 0xc0000e2ae0, 0xc00055bec8)
        /go/src/github.com/flannel-io/flannel/vendor/k8s.io/apimachinery/pkg/runtime/serializer/streaming/streaming.go:77 +0x89
k8s.io/client-go/rest/watch.(*Decoder).Decode(0xc0004f77a0, 0xc00055bf68, 0x8, 0x2484700, 0xc00040c300, 0x0, 0x0)
        /go/src/github.com/flannel-io/flannel/vendor/k8s.io/client-go/rest/watch/decoder.go:49 +0x6e
k8s.io/apimachinery/pkg/watch.(*StreamWatcher).receive(0xc000146ac0)
        /go/src/github.com/flannel-io/flannel/vendor/k8s.io/apimachinery/pkg/watch/streamwatcher.go:104 +0x147
created by k8s.io/apimachinery/pkg/watch.NewStreamWatcher
        /go/src/github.com/flannel-io/flannel/vendor/k8s.io/apimachinery/pkg/watch/streamwatcher.go:71 +0xbe

rax    0xca
rbx    0x3338dc0
rcx    0x46f303
rdx    0x0
rdi    0x3338f08
rsi    0x80
rbp    0x7ffe8c5d1340
rsp    0x7ffe8c5d12f8
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0x3
r13    0x33384a0
r14    0x6
r15    0x10
rip    0x46f301
rflags 0x286
cs     0x33
fs     0x0
gs     0x0

**Comment by lsorense** [comment]
I discovered another process was sometimes deleting routes it didn't recognize, so this is not flannel's fault at all.
