### ISSUE TITLE
Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or  nil pointer dereference)

### ISSUE THREAD

**Issue by Mao-sh** [flannel-io/flannel#1789]
## Current Behavior

```
I0809 03:03:50.250934       1 main.go:211] CLI flags config: {etcdEndpoints:http://192.168.16.189:2379 etcdPrefix:/coreos.com/network etcdKeyfile:/etcd-key.p
em etcdCertfile:/etcd.pem etcdCAFile:/etcd-ca.pem etcdUsername: etcdPassword: version:false kubeSubnetMgr:true kubeApiUrl: kubeAnnotationPrefix:flannel.alpha.coreos.com kubeConfigFile:/kubeconfig iface:[eth0] ifaceRegex:[] ipMasq:true ifaceCanReach: subnetFile:/run/flannel/subnet.env publicIP: publicIPv6: subnetLeaseRenewMargin:60 healthzIP:0.0.0.0 healthzPort:0 iptablesResyncSeconds:5 iptablesForwardRules:true netConfPath:/etc/kube-flannel/net-conf.json setNodeNetworkUnavailable:true useMultiClusterCidr:false}I0809 03:03:50.265070       1 kube.go:144] Waiting 10m0s for node controller to sync
I0809 03:03:50.265108       1 kube.go:485] Starting kube subnet manager
I0809 03:03:50.267188       1 kube.go:506] Creating the node lease for IPv4. This is the n.Spec.PodCIDRs: [172.16.0.0/24]
I0809 03:03:50.267214       1 kube.go:539] Creating the node lease for IPv6. This is the n.Spec.PodCIDRs: [172.16.0.0/24]
E0809 03:03:50.267287       1 runtime.go:79] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or 
nil pointer dereference)goroutine 34 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x18705a0?, 0x29125e0})
	/go/src/github.com/flannel-io/flannel/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:75 +0x99
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc00061c000?})
	/go/src/github.com/flannel-io/flannel/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:49 +0x75
panic({0x18705a0, 0x29125e0})
	/usr/local/go/src/runtime/panic.go:884 +0x212
github.com/flannel-io/flannel/pkg/ip.FromIP6Net(0xc000614540?)
	/go/src/github.com/flannel-io/flannel/pkg/ip/ip6net.go:166 +0x18
github.com/flannel-io/flannel/pkg/subnet/kube.(*kubeSubnetManager).nodeToLease(_, {{{0x0, 0x0}, {0x0, 0x0}}, {{0xc0000493f8, 0x17}, {0x0, 0x0}, {0x0, ...}, .
..}, ...})	/go/src/github.com/flannel-io/flannel/pkg/subnet/kube/kube.go:553 +0x446
github.com/flannel-io/flannel/pkg/subnet/kube.(*kubeSubnetManager).handleAddLeaseEvent(0xc000532100, 0x0, {0x1a81380?, 0xc0004b56c0})
	/go/src/github.com/flannel-io/flannel/pkg/subnet/kube/kube.go:263 +0x125
github.com/flannel-io/flannel/pkg/subnet/kube.newKubeSubnetManager.func3({0x1a81380?, 0xc0004b56c0?})
	/go/src/github.com/flannel-io/flannel/pkg/subnet/kube/kube.go:202 +0x32
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)
	/go/src/github.com/flannel-io/flannel/vendor/k8s.io/client-go/tools/cache/controller.go:232
k8s.io/client-go/tools/cache.processDeltas({0x1d24be8, 0xc000206f78}, {0x7f48f0087008, 0xc000604000}, 0x0, {0xc0005251c0?, 0x1, 0xc0001fe101?})
	/go/src/github.com/flannel-io/flannel/vendor/k8s.io/client-go/tools/cache/controller.go:439 +0x2a7
k8s.io/client-go/tools/cache.newInformer.func1({0x1893ae0?, 0xc0000128e8?})
	/go/src/github.com/flannel-io/flannel/vendor/k8s.io/client-go/tools/cache/controller.go:489 +0x5b
k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop(0xc0003a8140, 0xc0006020c0)
	/go/src/github.com/flannel-io/flannel/vendor/k8s.io/client-go/tools/cache/delta_fifo.go:554 +0x596
k8s.io/client-go/tools/cache.(*controller).processLoop(0xc000606000)
	/go/src/github.com/flannel-io/flannel/vendor/k8s.io/client-go/tools/cache/controller.go:184 +0x36
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x40f3d9?)
	/go/src/github.com/flannel-io/flannel/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:157 +0x3e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x12e7745?, {0x1d0f1a0, 0xc000602120}, 0x1, 0x0)
	/go/src/github.com/flannel-io/flannel/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:158 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000606068?, 0x3b9aca00, 0x0, 0xc0?, 0x7f48f0087090?)
	/go/src/github.com/flannel-io/flannel/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:135 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/go/src/github.com/flannel-io/flannel/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:92
k8s.io/client-go/tools/cache.(*controller).Run(0xc000606000, 0x0)
	/go/src/github.com/flannel-io/flannel/vendor/k8s.io/client-go/tools/cache/controller.go:155 +0x2c6
github.com/flannel-io/flannel/pkg/subnet/kube.(*kubeSubnetManager).Run(0xc000532100, {0x1d250c8, 0xc00004c020})
	/go/src/github.com/flannel-io/flannel/pkg/subnet/kube/kube.go:486 +0x75
created by github.com/flannel-io/flannel/pkg/subnet/kube.NewSubnetManager
	/go/src/github.com/flannel-io/flannel/pkg/subnet/kube/kube.go:142 +0x57b
E0809 03:03:50.267346       1 runtime.go:79] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or 
nil pointer dereference)goroutine 34 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x18705a0?, 0x29125e0})
	/go/src/github.com/flannel-io/flannel/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:75 +0x99
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc000636fb0?})
	/go/src/github.com/flannel-io/flannel/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:49 +0x75
panic({0x18705a0, 0x29125e0})
	/usr/local/go/src/runtime/panic.go:884 +0x212
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc00061c000?})
	/go/src/github.com/flannel-io/flannel/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:56 +0xd7
panic({0x18705a0, 0x29125e0})
	/usr/local/go/src/runtime/panic.go:884 +0x212
github.com/flannel-io/flannel/pkg/ip.FromIP6Net(0xc000614540?)
	/go/src/github.com/flannel-io/flannel/pkg/ip/ip6net.go:166 +0x18
github.com/flannel-io/flannel/pkg/subnet/kube.(*kubeSubnetManager).nodeToLease(_, {{{0x0, 0x0}, {0x0, 0x0}}, {{0xc0000493f8, 0x17}, {0x0, 0x0}, {0x0, ...}, .
..}, ...})	/go/src/github.com/flannel-io/flannel/pkg/subnet/kube/kube.go:553 +0x446
github.com/flannel-io/flannel/pkg/subnet/kube.(*kubeSubnetManager).handleAddLeaseEvent(0xc000532100, 0x0, {0x1a81380?, 0xc0004b56c0})
	/go/src/github.com/flannel-io/flannel/pkg/subnet/kube/kube.go:263 +0x125
github.com/flannel-io/flannel/pkg/subnet/kube.newKubeSubnetManager.func3({0x1a81380?, 0xc0004b56c0?})
	/go/src/github.com/flannel-io/flannel/pkg/subnet/kube/kube.go:202 +0x32
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)
	/go/src/github.com/flannel-io/flannel/vendor/k8s.io/client-go/tools/cache/controller.go:232
k8s.io/client-go/tools/cache.processDeltas({0x1d24be8, 0xc000206f78}, {0x7f48f0087008, 0xc000604000}, 0x0, {0xc0005251c0?, 0x1, 0xc0001fe101?})
	/go/src/github.com/flannel-io/flannel/vendor/k8s.io/client-go/tools/cache/controller.go:439 +0x2a7
k8s.io/client-go/tools/cache.newInformer.func1({0x1893ae0?, 0xc0000128e8?})
	/go/src/github.com/flannel-io/flannel/vendor/k8s.io/client-go/tools/cache/controller.go:489 +0x5b
k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop(0xc0003a8140, 0xc0006020c0)
	/go/src/github.com/flannel-io/flannel/vendor/k8s.io/client-go/tools/cache/delta_fifo.go:554 +0x596
k8s.io/client-go/tools/cache.(*controller).processLoop(0xc000606000)
	/go/src/github.com/flannel-io/flannel/vendor/k8s.io/client-go/tools/cache/controller.go:184 +0x36
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x40f3d9?)
	/go/src/github.com/flannel-io/flannel/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:157 +0x3e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x12e7745?, {0x1d0f1a0, 0xc000602120}, 0x1, 0x0)
	/go/src/github.com/flannel-io/flannel/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:158 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000606068?, 0x3b9aca00, 0x0, 0xc0?, 0x7f48f0087090?)
	/go/src/github.com/flannel-io/flannel/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:135 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/go/src/github.com/flannel-io/flannel/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:92
k8s.io/client-go/tools/cache.(*controller).Run(0xc000606000, 0x0)
	/go/src/github.com/flannel-io/flannel/vendor/k8s.io/client-go/tools/cache/controller.go:155 +0x2c6
github.com/flannel-io/flannel/pkg/subnet/kube.(*kubeSubnetManager).Run(0xc000532100, {0x1d250c8, 0xc00004c020})
	/go/src/github.com/flannel-io/flannel/pkg/subnet/kube/kube.go:486 +0x75
created by github.com/flannel-io/flannel/pkg/subnet/kube.NewSubnetManager
	/go/src/github.com/flannel-io/flannel/pkg/subnet/kube/kube.go:142 +0x57b
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x77bf78]

goroutine 34 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc000636fb0?})
	/go/src/github.com/flannel-io/flannel/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:56 +0xd7
panic({0x18705a0, 0x29125e0})
	/usr/local/go/src/runtime/panic.go:884 +0x212
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc00061c000?})
	/go/src/github.com/flannel-io/flannel/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:56 +0xd7
panic({0x18705a0, 0x29125e0})
	/usr/local/go/src/runtime/panic.go:884 +0x212
github.com/flannel-io/flannel/pkg/ip.FromIP6Net(0xc000614540?)
	/go/src/github.com/flannel-io/flannel/pkg/ip/ip6net.go:166 +0x18
github.com/flannel-io/flannel/pkg/subnet/kube.(*kubeSubnetManager).nodeToLease(_, {{{0x0, 0x0}, {0x0, 0x0}}, {{0xc0000493f8, 0x17}, {0x0, 0x0}, {0x0, ...}, .
..}, ...})	/go/src/github.com/flannel-io/flannel/pkg/subnet/kube/kube.go:553 +0x446
github.com/flannel-io/flannel/pkg/subnet/kube.(*kubeSubnetManager).handleAddLeaseEvent(0xc000532100, 0x0, {0x1a81380?, 0xc0004b56c0})
	/go/src/github.com/flannel-io/flannel/pkg/subnet/kube/kube.go:263 +0x125
github.com/flannel-io/flannel/pkg/subnet/kube.newKubeSubnetManager.func3({0x1a81380?, 0xc0004b56c0?})
	/go/src/github.com/flannel-io/flannel/pkg/subnet/kube/kube.go:202 +0x32
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)
	/go/src/github.com/flannel-io/flannel/vendor/k8s.io/client-go/tools/cache/controller.go:232
k8s.io/client-go/tools/cache.processDeltas({0x1d24be8, 0xc000206f78}, {0x7f48f0087008, 0xc000604000}, 0x0, {0xc0005251c0?, 0x1, 0xc0001fe101?})
	/go/src/github.com/flannel-io/flannel/vendor/k8s.io/client-go/tools/cache/controller.go:439 +0x2a7
k8s.io/client-go/tools/cache.newInformer.func1({0x1893ae0?, 0xc0000128e8?})
	/go/src/github.com/flannel-io/flannel/vendor/k8s.io/client-go/tools/cache/controller.go:489 +0x5b
k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop(0xc0003a8140, 0xc0006020c0)
	/go/src/github.com/flannel-io/flannel/vendor/k8s.io/client-go/tools/cache/delta_fifo.go:554 +0x596
k8s.io/client-go/tools/cache.(*controller).processLoop(0xc000606000)
	/go/src/github.com/flannel-io/flannel/vendor/k8s.io/client-go/tools/cache/controller.go:184 +0x36
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x40f3d9?)
	/go/src/github.com/flannel-io/flannel/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:157 +0x3e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x12e7745?, {0x1d0f1a0, 0xc000602120}, 0x1, 0x0)
	/go/src/github.com/flannel-io/flannel/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:158 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000606068?, 0x3b9aca00, 0x0, 0xc0?, 0x7f48f0087090?)
	/go/src/github.com/flannel-io/flannel/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:135 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/go/src/github.com/flannel-io/flannel/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:92
k8s.io/client-go/tools/cache.(*controller).Run(0xc000606000, 0x0)
	/go/src/github.com/flannel-io/flannel/vendor/k8s.io/client-go/tools/cache/controller.go:155 +0x2c6
github.com/flannel-io/flannel/pkg/subnet/kube.(*kubeSubnetManager).Run(0xc000532100, {0x1d250c8, 0xc00004c020})
	/go/src/github.com/flannel-io/flannel/pkg/subnet/kube/kube.go:486 +0x75
created by github.com/flannel-io/flannel/pkg/subnet/kube.NewSubnetManager
	/go/src/github.com/flannel-io/flannel/pkg/subnet/kube/kube.go:142 +0x57b
```

## Your Environment

* Flannel version: 0.21.3
* Backend used (e.g. vxlan or udp): vxlan
* Etcd version: 3.4.9
* Kubernetes version (if used): 1.21.14
* Operating System and version: centos7.9

Has anyone encountered such a problem? Please guide!

**Comment by Mao-sh** [comment]
I enabled dual stack support for kube apiserver kube controller manager kubelet kube proxy, and then specified in the Flannel configuration file to enable ipv6.The same issue was reported when using the latest version of 0.22.1。
Enable the ipv6 configuration as follows:
  net-conf.json: |
    {
      "Network": "172.16.0.0/12",
      "Backend": {
        "Type": "vxlan"
      },
      "EnableIPv6": true,
      "IPv6Network": "fc00::/48"
    }

**Comment by rbrtbnfgl** [comment]
How do you run kubeadm? It seems like the IPv6 is missing from the node spec.

**Comment by Mao-sh** [comment]
My environment is a binary deployment cluster. What methods will be called on the node network card when Flannel is started? The server is a cloud host purchased from a cloud vendor and has ipv6 enabled

**Comment by rbrtbnfgl** [comment]
Flannel uses the CIDR configured by kubernetes the same cidr configured on flannel has to be configured on the controller

**Comment by Mao-sh** [comment]
Is it related to creating subnets and local network cards when Flannel starts?

**Comment by rbrtbnfgl** [comment]
I am missing something on your setup. When you start Kubernetes before running Flannel on kube-controller-manager you should configure `--cluster-cidr` flag with the same CIDR that you configured on Flannel.

**Comment by Mao-sh** [comment]
The cidr I configured in kube controller manager is: --cluster-cidr=172.16.0.0/12,fc00::/48

**Comment by rbrtbnfgl** [comment]
Could you check the controller logs? The IPv6 somehow wasn't accepted and the node didn't get the CIDR.

**Comment by Mao-sh** [comment]
Thank you very much for your suggestion! My problem here is that due to node network issues, Flannel failed to load CIDR
